### ISSUE TITLE
[ISSUE] Jsoup connect시 인증서 오류

### ISSUE THREAD

**Issue by JustHm** [JungHm/AnuTool#1]
connect 시 인증서 오류로 페이지가 로드되지 않음.

**Comment by JustHm** [comment]
6

**Comment by JustHm** [comment]
W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err:     at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)

SSL 인증서 오류?  인거 같음

**Comment by JustHm** [comment]
https://derveljunit.tistory.com/280 참고
SSL 에러를 우회적으로 인증하는 방법

**Comment by JustHm** [comment]
https://developer.android.com/training/articles/security-ssl?hl=ko
android studio Document SSL 인증 방법

**Comment by JungHm** [comment]
close #2
